### ISSUE TITLE
linux not detecting remarkable 2

### ISSUE THREAD

**Issue by helpmeMAHORAGAheelp** [ddvk/remarkable2-recovery#28]
Hello! I have this really weird issue, I have 5pin pogo cable from aliexpress and a cable with B1 to B5 with 5.1k 0,25A resistor, linux cant find it or read it, windows only reads it as an undefined device. First I tried B8 to B12 using 10k resistor,but it didnt worked out either. Im hoping that you can help me reach some kind of progress, i actually runned out of options
Thank you <3

**Comment by Eeems** [comment]
Could you expand on what you mean by Linux can't read it? What is the dmesg output?

**Comment by helpmeMAHORAGAheelp** [comment]
I did it because b8 to b12 didnt work, i mean does it input a device in special mode or smth?
Also dmesg -w keep showing "failed to send h2c command".

**Comment by Eeems** [comment]
b8 to b12 is what uboot is looking for to put it into download mode. I've gone through the recovery process myself at this point, and those are the pins I connected with a 10k resistor.

> Also dmesg -w keep showing "failed to send h2c command".

Is that the only output? Or is there more? I would expect there to be more.

**Comment by helpmeMAHORAGAheelp** [comment]
![Zrzut ekranu z 2024-05-27 09-27-37](https://github.com/ddvk/remarkable2-recovery/assets/170731808/5fcf7784-4b02-4b05-a7af-9bbe9b5dca47)


> b8 to b12 is what uboot is looking for to put it into download mode. I've gone through the recovery process myself at this point, and those are the pins I connected with a 10k resistor.
I will try it in a moment

**Comment by Eeems** [comment]
Have you verified that your pogo connector is in the correct orientation? VCC should be the closest pin to the usb-c port

**Comment by helpmeMAHORAGAheelp** [comment]
![IMG_20240527_094029](https://github.com/ddvk/remarkable2-recovery/assets/170731808/e930353e-9a09-4781-bcc4-167f1fd13a68)

**Comment by Eeems** [comment]
The reason `imx_usb` is failing, is because the device is still not in download mode. You need to see the `USB HID v1.10 Device [Freescale SemiConductor Inc SE Blank ULT1]` line in `dmesg`.

It looks like you have two resistors on the breakout board. You should only have the one 10k resistor between B8 and B12. You'll need to make sure your usb-c breakout board is the right way up, as orientation matters.

Here is what my setup looked like, but I have a different breakout board.
![image](https://github.com/ddvk/remarkable2-recovery/assets/1176979/0bab042b-c851-4a51-b6b8-acf866bb89fd)
![image](https://github.com/ddvk/remarkable2-recovery/assets/1176979/250929c8-970f-47a2-b655-260c9f5ff19f)
The resistor is missing in the second photo, as I was already in recovery mode and had removed the resistor before running `imx_usb`.

**Comment by helpmeMAHORAGAheelp** [comment]
I did b8 to b12 and now remarkable is lagged and i cannot turn it off.
dmesg -w and imx_usb still dont work

**Comment by helpmeMAHORAGAheelp** [comment]
UPDATE
![Zrzut ekranu z 2024-05-27 14-16-54](https://github.com/ddvk/remarkable2-recovery/assets/170731808/18ac7920-c260-49d4-b7d0-6946cd1169da)

remarkable is no longer lagged and its showing "remarkable is starting" without loading bar
dmesg -w still show "failed to send h2c command" and "firmware failed to leave lps state"

**Comment by Eeems** [comment]
What do you mean by lagging? Your device should be off at first before you plug in the usb-c breakout board. As per the instructions in the readme.

> how does the recovery mode look like(does it show smt on remarkable?)

The screen will not display anything. You will only know based on the dmesg output.

> How long the programming takes?

Programming?

> Do you have to take usb out after the detection or before???

B8-B12 need to stay in until after it's detected the device in download mode. Then you can take it out, and then run `imx_usb`. Which is what the steps in the readme say.

**Comment by helpmeMAHORAGAheelp** [comment]
Tysm for trying to help :3
